version: "3.11"

services:
  postgres:
    container_name: postgres
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=games
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testPasswor15.

volumes:
  dev-db-data: